### PR TITLE
Report verifiedLength in tellStatus

### PR DESCRIPTION
**Pull request by kkartaltepe**
Allows RPC clients to view progress of the check integrity step.

I didn't notice any tests for TellStatus so I havn't tried to make any for this branch. One other modification I would like to make but wasn't sure how to implement would be reporting if a particular download was in the queue to have its integrity checked (in the CheckIntegrityMan deque). If you had any thoughts on how to do that I'd be happy to implement it.

Please also provide any feedback or changes you like to see made to this PR to be merged.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Ahh, found i was missing cppunit, sorry if the failed builds caused any email spam. Hopefully I can get a passing build now that I can run the tests locally.

**Comment by tatsuhiro-t** [comment]
Thank you for PR!  Could you debug the unit test error found in travis?

**Comment by kkartaltepe** [comment]
Yes, I was thinking about some other ways to get around being unable to
check the references as I'm having issues due to SequentialPicker using
unique_ptr's. I will work on it again this coming weekend.

**Comment by kkartaltepe** [comment]
Looks like there was a case where getCheckIntegrityMan could return null which was causing the segfaults. At this point I have all the info I want being reported in tellStatus except whether a download has had its integrity checked or not. I think I can just use 'Seeding' for my purposes but it was something I thought about when writing this PR.

**Comment by tatsuhiro-t** [comment]
Sorry for the late reply.  Is this PR ready for merge?

**Comment by tatsuhiro-t** [comment]
This PR has been merged with some amends.  Thank you!

**Comment by kkartaltepe** [comment]
Thank you for the merge!

**Pull request merged**
