### PR TITLE
multiple interface support for link aggregation

### PR DESCRIPTION
**Pull request by sarim**
Code is pretty self explanatory. This adds support for using more than one network interfaces.
```
aria2c --multiple-interface=eth0,eth1 http://url.....
```

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR.  This looks very interesting.  At a glance, it chooses interface in round robin manner, right?  I'll review this and comment if any.

**Comment by sarim** [comment]
Yes, round robin. It just loops through the interface list when a new connection is being established. Ratio based load balancing can be implemented, but too complex for me :P Given enough thread, I use 8 (-s 8 -x 8)   i don't think it'll be an issue.

In my case, my two connection are both of same speed.

**Comment by tatsuhiro-t** [comment]
OK, no problem.  PR looks good.  Could you squash commits into one?  Then I'll merge this PR.  Thank you.

**Comment by sarim** [comment]
Ok, squashed commits into one. I think i did it. Please check now.

**Comment by tatsuhiro-t** [comment]
Thank you very much.  Merged now.

**Pull request merged**
