### PR TITLE
Allow netrc-path to be specified in the config file

### PR DESCRIPTION
**Pull request by zi0r**
Allow us to specify an alternate path for the netrc file.  By default, this option is hidden from us and defaults to HOME/.netrc

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Please don't mind about travis error; I tested travis but forgot to disable it.

Since we are a bit picky about netrc file permission, it would be better to limit it to command-line option only (`op->setInitialOption(true);`).
Also we have to define TEXT_NETRC_PATH in usage_text.h and describe its usage.

**Comment by zi0r** [comment]
Id prefer that we are able to specify this in the config file as well as the command-line.

**Comment by tatsuhiro-t** [comment]
If all options available in command-line except for --conf option is also available in config file for free.

**Comment by zi0r** [comment]
I did not understand the last comment.  Are you expecting action from me?

**Comment by tatsuhiro-t** [comment]
Please remove 2 lines below:
```
+    op->setChangeGlobalOption(true);
+    op->setChangeOptionForReserved(true);
```

**Comment by tatsuhiro-t** [comment]
Sorry, `op->setInitialOption(true);` should be also removed, since --netrc is global option and parsed from command-line and configuration file only.

**Comment by tatsuhiro-t** [comment]
After everything, please squash commits into one, then I'll do merge. Thank you.

**Comment by tatsuhiro-t** [comment]
I squashed and editted a bit (removing the suggested line above), and merged this PR via ceee04cfe8b870021a7964acb68bce00d74490db.
Thank you.

**Pull request closed without merging**
