### PR TITLE
Make script compatible with both Python 2 and 3

### PR DESCRIPTION
**Pull request by wasamasa**
See #398.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you!
I got error after applying this patch.  If I replace "print" with "print_function" it works.
```diff
diff --git a/doc/manual-src/en/mkapiref.py b/doc/manual-src/en/mkapiref.py
index fdf2a65..0354594 100755
--- a/doc/manual-src/en/mkapiref.py
+++ b/doc/manual-src/en/mkapiref.py
@@ -33,7 +33,7 @@
 #
 # Generates API reference from C++ source code.
 import re, sys, argparse
-from __future__ import print
+from __future__ import print_function
 
 class FunctionDoc:
     def __init__(self, name, content, domain):
```

**Comment by wasamasa** [comment]
OK, fixed.

**Comment by tatsuhiro-t** [comment]
Thanks.  I forgot to mention that we have to put `from _future__ imports` before any imports.

**Comment by wasamasa** [comment]
Anything else?

**Comment by tatsuhiro-t** [comment]
LGTM.  Merged now. Thank you!

**Pull request merged**
