### PR TITLE
Assertion failed in SimpleRandomizer.cc:93

### PR DESCRIPTION
**Pull request by nmaier**
When I try to download any file, I get this error: 
```
aria2c: SimpleRandomizer.cc:93: void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t): Assertion `rv >= 0 && (size_t)rv == len' failed.
---------
=> aria2c --version 
aria2 version 1.18.9
Copyright (C) 2006, 2014 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 libxml2/2.9.2 sqlite3/3.8.8.1 GnuTLS/3.3.12 nettle GMP/6.0.0 c-ares/1.10.0
Compiler: gcc 4.9.2 20141224 (prerelease)
  built by   x86_64-unknown-linux-gnu
  on         Feb  2 2015 08:14:18
System: Linux 3.15.8-1-ARCH #1 SMP PREEMPT Fri Aug 1 08:51:42 CEST 2014 x86_64

Report bugs to https://github.com/tatsuhiro-t/aria2/issues
Visit http://aria2.sourceforge.net/
--------
```
Let me know if any further data or log is needed.

### CODE REVIEW

**Comment by nmaier** [comment]
@tatsuhiro-t Any objections?

**Comment by tatsuhiro-t** [comment]
No objection if it fixes this issue.

**Comment by nmaier** [comment]
@nkhdiscovery Any chance you can try this branch yourself?

**Comment by nkhdiscovery** [comment]
@tatsuhiro-t @nmaier I've a total broken system these days as I was upgrading my archlinux, I try to test this as soon as possible.

**Comment by ClaudiaJ** [comment]
Branch built successfully on my Arch vm through Linode, fails with following error number:
>getrandom returned an unhandled error: 38
>aria2c: SimpleRandomizer.cc:93: void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t): Assertion `rv >= 0 && (size_t)rv == len' failed.

**Comment by nmaier** [comment]
hmm. interesting. `38` should be `ENOSYS` aka. not implemented. That shouldn't happen unless the linux headers and the kernel are a mismatch.

**Comment by nmaier** [comment]
Alright, I'll write some more code to handle ENOSYS gracefully and fall back to the generic implementation if encountered.

**Comment by ClaudiaJ** [comment]
I wonder if it might be directly relating to how the kernel is managed on Linode configurations. I haven't reboot into anything newer than the following in almost a month and a half:
>Linux dev 3.16.7-x86_64-linode49 #3 SMP Fri Nov 14 16:55:37 EST 2014 x86_64 GNU/Linux

A description of how Linode's kernels are handled can be found [here](https://github.com/yardenac/linux-linode)

**Comment by nmaier** [comment]
@ClaudiaJ Yeah, that's the problem right there. You got the usual 3.18 linux headers, but the kernel is in fact only 3.16 (from Linode). Looking closely at the output from @nkhdiscovery it says `Linux 3.15.8-1-ARCH`, so same issue.

@ClaudiaJ and/or @nkhdiscovery can you retry this branch? I pushed again and hope this latest commit handles the missing syscall/implementation gracefully now.

**Comment by ClaudiaJ** [comment]
Branch is built successfully on my Linode vm, and a quick test download of some diff from gist is also successful.
I'll also pick up a newer kernel this weekend.

**Comment by nkhdiscovery** [comment]
@ClaudiaJ @nmaier @tatsuhiro-t  I updated my kernel and it works fine now, I think I can't risk to reproduce the error right now by downgrading my kernel as I'm in the middle of my master project... Thank you guys for your quick response :)

**Comment by Haocen** [comment]
Run into similar problem since version 1.26.1:

```
[/Aria2] # ./bin/aria2c -v
aria2 version 1.30.0
Copyright (C) 2006, 2016 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.1.0 sqlite3/3.11.0 OpenSSL/1.0.2g c-ares/1.10.0 libssh2/1.5.0
Compiler: gcc 5.4.0 20160609
  built by   x86_64-pc-linux-gnu
  on         Jan  5 2017 23:33:21
System: Linux 3.12.6 #1 SMP Wed Dec 14 04:23:22 CST 2016 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
<-conf-path=./Aria2/a.conf 
aria2c: SimpleRandomizer.cc:117: void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t): Assertion `rv >= 0 && (size_t)rv == len' failed.
Aborted
```

**Comment by tatsuhiro-t** [comment]
@Haocen thank you. #823 will fix it.

**Pull request closed without merging**
